- name: Create directory
  ansible.builtin.file:
    path: ../dist
    state: directory
    mode: "0644"

- name: Template wireguard config wg{{ item.NAME }}
  ansible.builtin.template:
    src: wg_client.conf.j2
    dest: "../dist/wg{{ item.NAME }}.conf"
    mode: "0644"
  loop: "{{ wireguard_configs }}"
