- name: Create directory
  ansible.builtin.file:
    path: /home/runner/work/vpn-infra/vpn-infra/ansible/dist/{{ SERVER_NAME }}
    state: directory
    mode: "0644"

- name: Template wireguard config wg{{ item.NAME }}
  ansible.builtin.template:
    src: wg_client.conf.j2
    dest: "/home/runner/work/vpn-infra/vpn-infra/ansible/dist/{{ SERVER_NAME }}/wg{{ item.NAME }}.conf"
    mode: "0644"
  loop: "{{ wireguard_configs }}"
