- name: Create directory
  ansible.builtin.file:
    path: ./dist/{{ SERVER_NAME }}
    state: directory
    mode: "0644"

- name: Template wireguard config wg{{ item.NAME }}
  ansible.builtin.template:
    src: wg_client.conf.j2
    dest: "./dist/{{ SERVER_NAME }}/wg{{ item.NAME }}.conf"
    mode: "0644"
  loop: "{{ wireguard_configs }}"
